### ISSUE TITLE
Problem converting some HTML codes

### ISSUE THREAD

**Issue by jorfermo** [mwaterfall/MWFeedParser#1]
Hi!

I'm using in a project your NSString+XMLEntities class but I'm having trouble in some conversions. For instance this text block (first line is before and second is after):

```
"de tama&ntilde;os variados, que permitir&aacute;n dise&ntilde;ar los distintos itinerarios."
"de tamaÑos variados, que permitirÁn diseÑar los distintos itinerarios."
```

It's converting the codes to the upper case version of that letter. It should be:
    "de tamaños variados, que permitirán diseñar los distintos itinerarios."

Any Idea why? Thank you!

**Comment by mwaterfall** [comment]
Hmm yes, I'm seeing that too. Just looking into it now!

**Comment by mwaterfall** [comment]
Okay that's all fixed and updated! Thanks for making me aware of the problem. It was an issue with case sensitivity when decoding the entity references.

**Comment by jorfermo** [comment]
Thank you!

Now it's working perfect.

Congrats for your great work.
