### ISSUE TITLE
Enclosures does not contain all media content

### ISSUE THREAD

**Issue by jonerickson** [mwaterfall/MWFeedParser#101]
I have been using MWFeedParser for quite some time and at this point, it does not parse all media content associated with the feed. In my case, if there is media attached, it only parses the first item. Any reason for this or quick fix?

**Comment by davidhlee** [comment]
Any news on this issue?

**Comment by jonerickson** [comment]
No, none yet.

**Comment by badalpub1991** [comment]
how to parse image in this framework ?
