### ISSUE TITLE
iOS 9 SSL Issues

### ISSUE THREAD

**Issue by Kfeavel** [mwaterfall/MWFeedParser#108]
Even if the original server has SSL (https://), MWFeedParser will return a non-secure http link, therefore rendering the parser useless.

**Comment by EvgenyKarkan** [comment]
Hi @Kfeavel 
I heard that NSURLConnection API will be deprecated since iOS 9.
So, on iOS 8 deployment target - MWFeedParser will work.
But, does it work on iOS 9 deployment target?
@mwaterfall any plans for NSURLSession support?

**Comment by Kfeavel** [comment]
@EvgenyKarkan In my experience, no, MWFeedParser won't work on iOS 9 unless you manually disable all SSL checks in your app using an Info.plist key.

**Comment by EvgenyKarkan** [comment]
Hello @Kfeavel 
Thanks for the answer, I understand.
Good luck.
