### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by VictorAlexander** [mwaterfall/MWFeedParser#11]
Wondering if there's anyway of caching the info from the feed. Thanks to iOS 4.0 it stays there for a bit, but disappears after a bit.

**Comment by mwaterfall** [comment]
You could implement your own caching by storing the feed data yourself and displaying that before your app then requests the latest feed data. MWFeedInfo and MWFeedItem both support the NSCoding protocol so you can persist them that way. Hope this helps!
