### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by VictorAlexander** [mwaterfall/MWFeedParser#12]
Hello! 

I was just wondering if you could implement caching, or give out a few hints on how to approach it, because I'm having trouble getting it to work... I attempted to implement caching the parsedItems, using the EGOCache (https://github.com/enormego/EGOCache) classes but to no avail... thanks in advance!

**Comment by mwaterfall** [comment]
Hi, please see: https://github.com/mwaterfall/MWFeedParser/issues/issue/11
