### ISSUE TITLE
stopParsing -> parse -> error

### ISSUE THREAD

**Issue by Ten13** [mwaterfall/MWFeedParser#14]
Hi

I have an situation where I need to stop parsing and then start parsing again immediately. I will get an error saying: "Cannot start parsing as parsing is already in progress".

It seems that even though you are calling the [delegate feedParserDidFinish] you forget to call [self parsingFinished]. This could be due to some async issues I cannot see.

Please advice,

Martin Lobger

**Comment by Ten13** [comment]
Oh BTW! Thanks for a great feed parser. I am using it extensively!

/Martin

**Comment by mwaterfall** [comment]
Hi Martin,

Glad to hear you like the parser :)

I'll take a look into that issue. I'm currently making a few improvements to the parser so hopefully when that's done it'll work better.

Best regards,
Michael

**Comment by lengoldenstein** [comment]
I've come across this too in stopParsing: and failWithErrorCode:.  Seems the 'parsing' boolean stays at YES.  I added calls to [self parsingFinished] in the two methods and that sets parsing = NO.  Everything then works as expected.
Excellent work on the parser indeed!

**Comment by mwaterfall** [comment]
Hey guys,

I've just pushed an update which should hopefully resolve the issue you're having.

Best regards,
Michael

**Comment by Ten13** [comment]
Hi Michael

I have downloaded your latest commit, and it seems to have solved my issue.
Thank you for your good work!

/Martin
