### ISSUE TITLE
cannot decode raw data

### ISSUE THREAD

**Issue by bluekite2000** [mwaterfall/MWFeedParser#15]
When I use this link
http://vnexpress.net/rss/gl/xa-hoi.rss
I receive an error
MWFeedParser[1888:207] Finished Parsing With Error: Error Domain=MWFeedParser Code=2 "cannot decode raw data" UserInfo=0x4d59880 {NSLocalizedDescription=cannot decode raw data}

I tried another link
http://www.salon.com/rss/all_salon.rss
and it worked.

**Comment by mwaterfall** [comment]
Hi there,

I've taken a look and it appears there is a problem with the RSS feed in question. When I try and preview it in Firefox I get the error:

> The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

In MWFeedParser, the error is coming straight from the NSURLConnection and no data is being returned for that URL.

Best regards,
Michael

**Comment by bluekite2000** [comment]
Thanks for your reply,
I added the feed to google reader and it worked fine.
Are you sure there is problem w/ the feed?
Dat

**Comment by mwaterfall** [comment]
Yes it was a problem with the feed, however they appear to have made some changes as it is now working. Try it again and let me know if you have any problems.

Thanks,
Michael
