### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by danielsteel** [mwaterfall/MWFeedParser#2]
Hey Waterfall,

Now the app / framework means that the application is always open in iOS4... Any plans to add a refresh button in there to re gather the data? 

Thanks
Dan

**Comment by mwaterfall** [comment]
Hi Dan,

Actually, disabling background execution is something I forgot to do!

A refresh button would be easy for you to implement. The demo app within this project is just a simple demonstration as to how one could use this framework, so features are kept to a minimum.

Thanks for getting in touch.

Michael

**Comment by danielsteel** [comment]
Thanks Michael, i will drop one in. One other thing the details been pulled into summary from my cells is loosing the case, so Month is becoming month and so on. Any ideas how i can stop this in the parse?

**Comment by mwaterfall** [comment]
I'm not sure about that, if you have an example feed URL I can take a look if you want?

**Comment by danielsteel** [comment]
Sure the URL is : http://spreadsheets.google.com/feeds/list/0Ap2FZ1qduFlYdDRGY3VlM2Z0YWZ4UFZsaGIyczdhelE/od6/public/basic

**Comment by mwaterfall** [comment]
It would appear that the feed data is all lowercase, so it's an issue with the original data or feed generation, not the parsing. You can see this by browsing to the feed in your web browser.

**Comment by danielsteel** [comment]
Oh dear school boy error!

**Comment by mwaterfall** [comment]
No worries ;)
