### ISSUE TITLE
Is it possible to get 1st 10 articles of a feed?

### ISSUE THREAD

**Issue by bluekite2000** [mwaterfall/MWFeedParser#20]
I dont want to download all the articles of the feed. The file is too big. I just want to download the 1st 10 and if the user wants more he can click on "Load more" and it will download more.

**Comment by mwaterfall** [comment]
The full feed contents must be downloaded for the XML document to be valid and the parsing to begin. However you are able to stop the parsing operation after the first item has been parsed (i.e. calling the -stopParsing the first time -feedParser:didParseFeedItem: is called). This will prevent the parser from parsing of the rest of the document. Hope this helps.

**Comment by bluekite2000** [comment]
The parsing doesnt take much time. its the downloading. Can I do parallel downloading? Or can I just download new articles (currently I m downloading a big feed every hour but usually 95% of the feed is old news ie. i have already downloaded and parsed them) Is then a way to just download articles that have NOT been downloaded before?

**Comment by mwaterfall** [comment]
Unfortunately I'm not aware of any easy way of doing this. I'm sure it's possible, however it's out of the scope of this project.

If you were to successfully merge previously downloaded data and new feed items, you could fork this project and pass the XML parser your own NSData object containing the new merged document.

Best of luck!

**Comment by bluekite2000** [comment]
I dont want to merge previously downloaded data and new feed items. Previously downloaded data has already been parsed. I dont want to parse it again. If a user refreshes, I want to download articles that have been recently published. Since you said you need to download the entire feed before you need to parse it, it sounds redundant since the app will have to parse articles it has parsed before.
