### ISSUE TITLE
Quick not thread-safe question?

### ISSUE THREAD

**Issue by dglancy** [mwaterfall/MWFeedParser#22]
Hello,
I noticed in the README that you mentioned that the parser is not thread-safe. I'm guessing this means that two threads can't access the same parser instance at the same time. My question: do you think its safe to have two parallel threads each with their own instance of the parser working simultaneously? Or would this also not be thread-safe?

Thanks again and especially for such a great open-sourced component.

**Comment by mwaterfall** [comment]
Hey Damien,

Yes you're right, it's not safe to access an instance from multiple threads at the same time, however using an isolated instance per-thread (in an NSOperation for example) is absolutely OK.

No problem, glad you're finding the parser useful :-)

Cheers!

**Comment by dglancy** [comment]
Wow, that's a quick response and excellent news. NSOperation is exactly where I'm headed!
