### ISSUE TITLE
read tag inside tag (<test>url='http://... name='name' </test>)

### ISSUE THREAD

**Issue by 22diabolo** [mwaterfall/MWFeedParser#24]
Hi,
i want to read url and name inside test tag (i think its called attribute ).
how can i read this? i know that i need to edit MWFeedParser.m but i dont know how..
thanks
22diabolo

**Comment by mwaterfall** [comment]
Hi there, 

This tag isn't a valid RSS/Atom tag and is not supported by MWFeedParser. Feel free to fork this project and make any modifications you require. Unfortunately I can't help you with this issue, but it shouldn't be hard to make this change.

Cheers,
Michael
