### ISSUE TITLE
Podcast Isse

### ISSUE THREAD

**Issue by renegade78** [mwaterfall/MWFeedParser#25]
Hi,

I cannot even begin to thank you for all the help your code has given me! I've extracted the URL of images and displayed them in the tableview, put them in a fancy detail view and I'm really pleased with the result!

The final element I'm having issues with is getting the URL of enclosures such as a podcast.

I know you don't have time to help in detail with individual issues but I was hoping you could just explain how I can extract it!

Many thanks in advance!

**Comment by mwaterfall** [comment]
Hi there,

Really glad to hear you're enjoying using the parser!

If the podcast information is provided as an enclosure then you can access that feed information via the `enclosures` attribute of the feed items. Information on this can be found in the readme under the heading "Available Data."

However, if the podcast media information is provided by some other means (in an unsupported element), then this data will not be available in the current version of the parser.

If you take a look at the raw feed data for the podcast you should be able to see how the information is provided.

Hope this helps!
