### ISSUE TITLE
Add class attribute to MWFeedItem

### ISSUE THREAD

**Issue by paul5** [mwaterfall/MWFeedParser#26]
Hi! Thanks for  your project!
I love it and i use it in my app. Now I need to add one class attribute in MWFeedItem. But when I create an object of this type, I can't access to the attribute that I create before. I can't understand why!
Can you help me? Thanks

**Comment by mwaterfall** [comment]
Hi Paul, I'm assuming this is related to your other issue which I have commented on, so I'll close this one.
