### ISSUE TITLE
GTMNSString+HTML I can't add class method!!

### ISSUE THREAD

**Issue by paul5** [mwaterfall/MWFeedParser#27]
I want do mod this file to do something else. In GTMNSString+HTML.h I add this code:
- (NSString *)getFirstImage; 
  in GTMNSString+HTML.m I add the implementation:
- (NSString *)getFirstImage {
  //Do something 
  
  ```
  return url;
  ```
  
  }

}
I use this with this code:

NSString *url = [item.summary getFirstImage];
But I received this warning,

422:21:{422:21-422:49}: warning: instance method '-getFirstImage' not found (return type defaults to 'id') [3]
Also in MWFeedItem.h I added

NSString *image; 

@property (nonatomic, copy) NSString *image;
And than in the implementation I added the @synthesize image; but when I try to use it with

MWFeedItem *item =[reader.feedItems objectAtIndex:index];  
item.image
i can't use it! why this?

**Comment by mwaterfall** [comment]
Hi there,

I'm not quite sure what you're trying to do. It would appear that this is an Objective-C programming issue rather than one relating to MWFeedParser, so unfortunately I'm unable to help you.

Best regards,
Michael
