### ISSUE TITLE
Memory leaks in FeedParser didEndElement

### ISSUE THREAD

**Issue by NathanHazout** [mwaterfall/MWFeedParser#29]
According to Instruments, there are memory leaks here, 
Within - (void)parser:(NSXMLParser *)parser didEndElement:(NSString *)elementName 
                                      namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qName

(around line 608)
// Remove newlines and whitespace from currentText
NSString *processedText = [currentText stringByRemovingNewLinesAndWhitespace];

(around line 622)
else if ([currentPath isEqualToString:@"/rss/channel/item/pubDate"]) { if (processedText.length > 0) item.date = [NSDate dateFromInternetDateTimeString:processedText formatHint:DateFormatHintRFC822]; processed = YES; }

(around line 692)
// Dispatch item to delegate
[self dispatchFeedItemToDelegate];

I've been trying to understand them but no luck so far.

**Comment by mwaterfall** [comment]
I've tested the demo project for leaks and I'm not seeing any. Could you provide more information such as the feed URL you're using so I can try and replicate it? It may well be leaks coming in from your project so it'll be good to test the feed on the demo project to get more information.

**Comment by mwaterfall** [comment]
I've closed the issue for now but if you come up with any more findings then we can reopen it.
