### ISSUE TITLE
Memory leak in parser

### ISSUE THREAD

**Issue by dbxfb** [mwaterfall/MWFeedParser#3]
Hello, there seems to be a memory leak in the parser:

MWFeedParser.m
line 330:
        self.item = [[MWFeedItem alloc] init];
should be:
        self.item = [[[MWFeedItem alloc] init] autorelease];

because both "alloc" and the "item" property (which has auto retain) retain the object...
in the end, it doesn't get freed with the single release in dealloc (or so it seems).

Thanks

**Comment by mwaterfall** [comment]
Hi, thanks for the message, I'll check it out!

**Comment by mwaterfall** [comment]
This leak, along with another in the MWFeedParser's -reset method has now been fixed and pushed! Thanks for letting me know :)
