### ISSUE TITLE
Thread-unsafety in NSDate+InternetDateTime.m

### ISSUE THREAD

**Issue by regexident** [mwaterfall/MWFeedParser#33]
`NSDateFormatter` is not threadsafe.

This causes MWFeedParser to crash when parsing dozens of feeds in parallel.

Adding

```
@synchronized(dateFormatter) {
    …
}
```

to both, `dateFromRFC822String:` and `dateFromRFC3339String:` fixed it.

But then again a static NSDateFormatter was probably chosen to be used in order to improve performance, which the `@synchronized(){…}` locks kind of destroy. Using non-static temporary NSDateFormatter instances would probably be a better choice.

**Comment by mwaterfall** [comment]
Ah, very true, thanks for reporting this! I'll look into it.

Yes the static `NSDateFormatter` was used for performance as the initialisation of a new formatter is very slow.

**Comment by mwaterfall** [comment]
I think the best option is to synchronise by the NSDate class. An NSDateFormatter instantiated on every call would slow a lot of things down. Thoughts?

**Comment by mwaterfall** [comment]
I've pushed a commit which should resolve this thread unsafety.

Let me know if it resolves the problems you've been having!

**Comment by regexident** [comment]
Looks like it solved it. Sorry for the delayed response. :(

**Comment by mwaterfall** [comment]
No worries about the delay!

I actually made another improvement just now (forgot to push it yesterday!). It should work a little better and only require 1 date formatter. Would it be possible for you to just make sure this works okay and doesn't cause any multithreading issues? I don't have a test case for that scenario!

Cheers!
