### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by renegade78** [mwaterfall/MWFeedParser#4]
Hi,

This isn't really an issue - more of a plea for help! I apologise if it's in the wrong section, I'm really new to this.

Basically, I was wondering how to add a "Refresh" button and whether or not it is possible to include images from the feeds?

Any help would be greatly appreciated!

**Comment by mwaterfall** [comment]
Hi there,

If a feed item contains HTML (including images) in it's content then you can access that information through the summary or content properties of the MWFeedItem object.

Refreshing would simply be a matter of creating a new MWFeedParser instance and re-parsing a URL. Unfortunately I cannot really help with individual implementations.

Best of luck though!

**Comment by renegade78** [comment]
Thank you for that. I realise you can't help with individual implementations but I was wondering if you could demonstrate the reload functionality on your source code. The image thing I will try and work out!

Obviously, I understand if you are unable to do this. I am grateful for the hard work you have already put in! If more developers were willing to share in this way, maybe the learning curve would be less steep!

Thanks again.

**Comment by mwaterfall** [comment]
Thanks for the kind words :)

I'll implement a refresh feature within the demo app sometime soon.

**Comment by renegade78** [comment]
Many thanks. I actually managed it so by not helping me, you really did help me!! I've come across your code mentioned a lot on forums, and it seems the most requested feature is adding images. Thanks again, I'm off to spend a few hours trying to solve the image problem myself - it is more rewarding than being handed the code!!

**Comment by mwaterfall** [comment]
Awesome, that's great :) Perhaps I shouldn't add a refresh button on the demo app after all! Oh right I wasn't aware of it being mentioned. If you have any links to hand I'd love to see what they're saying. I found one mention of the parser talking about images and formatting so I added a comment in reply!

**Comment by renegade78** [comment]
I'll find them later and post them here. One was in French - that really tested my old A level skills!

I've turned your app into a tab bar app with numerous feeds and altered the formatting slightly. I think improving the look of the detailview is my next job and then getting the images from my feeds! All thanks to you for giving me a starting point!!

**Comment by renegade78** [comment]
Okay, I give up!!!

I'm trying to parse images from my wordpress blog into the tableview and detailview and I have spent the last 2 days trying to solve this!

I know you said you can't help with individual implementations but if I ask really nicely?!!!

Another thing was my refresh method. It works - kind of...

Basically, I've added a refresh button and I recall the method in the viewdidload example. However, if you scrool the tableview whilst it is refreshing, the app crashes with an "out of range" error. I'm presuming that this is because as it is refreshing, the table no longer has as many cells as I've told it it has. I'm pretty new to this but I am trying!

Any help with either of these issues would be greatly appreciated!

**Comment by ialphan** [comment]
It should also crash when you refresh and select a cell. 

I just started implementing MWFeedParser to my application. So far everything looks good, thanks @mwaterfall.

**Comment by ialphan** [comment]
@mwaterfall Refresh function would be a good add on to this parser.

**Comment by renegade78** [comment]
To get around it crashing, I added if (items => 1) before setting up the cells. It seems to get around the cells being filled from an empty array during parsing.

**Comment by renegade78** [comment]
Sorry, should have put : if (items.count => 1)...

**Comment by ialphan** [comment]
That should be "if (items.count >= 1)".

**Comment by mwaterfall** [comment]
Hey guys, just to let you know I'm going to be pushing an update in the next few days which will, among other things, include a refresh button, and demonstrate how to view item content as styled HTML as well as in plain text. I'm pretty busy but I'll try and get it out as soon as I can.

**Comment by ialphan** [comment]
That's great news. Hope to see the release soon. Thanks!

**Comment by renegade78** [comment]
That would be great! Thanks!

**Comment by mwaterfall** [comment]
Just to let you know I've pushed a commit with a refresh button in the demo app. I haven't got around to the HTML rendering of the feed summary/content but I'll get around to that sometime soon!

**Comment by renegade78** [comment]
Great, much appreciated!

**Comment by bluekite2000** [comment]
any idea on when the HTML rendering of the feed summary/content will be released?
Currently the article i get from techcrunch is all jumbled into 1 big messy parapgraph.
btw why did you have it as plain text (i saw you used stringByConvertingHTMLToPlainText?) insteald of html. it looks so much nicer w/ html

**Comment by mwaterfall** [comment]
@bluekite2000 Feel free to use the raw data in item.summary or item.content. You can plug this straight into a UIWebView to view the rendered HTML for the feed items.

**Comment by bluekite2000** [comment]
Yeah I m debating whether to convert to plain text then show (like what you have right now) or display in uiwebview as html? What is your opinion on this (pros vs cons)?

**Comment by mwaterfall** [comment]
This would be totally implementation specific so I can't advise one or the other. Just use whatever is best for the feeds you're reading and how you're using the parser.

**Comment by bluekite2000** [comment]
I think I ll use uiwebview like you said.
Is it better to keep
DetailTableViewController : UITableViewController
then change the summary section to display html (ie using uiwebview)
or should I do 
DetailTableViewController : UIWebViewController

What method do you think will respond in a faster app?

**Comment by mwaterfall** [comment]
It's totally up to you mate, it depends on what you want to achieve with your project and how you want it to look. Unfortunately I dont have time to help with specific requests unrelated to the workings of the parser itself. Best of luck though.
