### ISSUE TITLE
Parsing of guid/id?

### ISSUE THREAD

**Issue by olihey** [mwaterfall/MWFeedParser#5]
Hej,

Any plans to add the parsing of the guid / id tag in MWFeedParser?

Oli

**Comment by mwaterfall** [comment]
Hi Oli, I'll look into parsing the guid / id tags and hopefully have it available in the next update of MWFeedParser. Thanks for getting in touch.

**Comment by olihey** [comment]
Cool, thanks a lot!

Oli

**Comment by mwaterfall** [comment]
I've added parsing of guid/id elements so this feature will be available when I push the next update ;)

**Comment by olihey** [comment]
Great! Works like a charm.
Thanks very much,
Oli
