### ISSUE TITLE
problem using NSString+HTML

### ISSUE THREAD

**Issue by testower** [mwaterfall/MWFeedParser#51]
I am trying to decode html entities from a string using your NSString+HTML category. GTMNSString+HTML is also imported.

I am using Xcode 4.3.2 with ios 5.1

Can you help?

 -[__NSCFString stringByDecodingHTMLEntities]: unrecognized selector sent to instance 0x6e65a40
 **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString stringByDecodingHTMLEntities]: unrecognized selector sent to instance 0x6e65a40'

**Comment by mwaterfall** [comment]
Have you `#imported` the `NSString+HTML.h` category into your code?

**Comment by testower** [comment]
Yes like this:

#import "NSString+HTML.h"

The GTMNSString+HTML is (sufficiently?) imported by NSString+HTML, so I assume I don't have to import it explicitly in my own code?

The following files are copied into my project:

GTMNSString+HTML.h
GTMNSString+HTML.m
NSString+HTML.h
NSString+HTML.m

Do I need anything else?

**Comment by testower** [comment]
Here's how I'm trying to use it:

``` objective-c
NSString *title = [[entry valueForKey:@"title"] stringByDecodingHTMLEntities];
```

**Comment by mwaterfall** [comment]
Have you checked that `[entry valueForKey:@"title"]` is an instance of `NSString`?

**Comment by testower** [comment]
Looks like it's actually NSMutableString, but could that be the problem? Can't check right now...

**Comment by testower** [comment]
I did a copy on the NSMutableString, which should return a regular NSString. It did not fix the problem.

**Comment by CMTaylor** [comment]
I'm getting an erro like this, too, after upgrading an old project to Xcode 4.3.2.  My error is:
-[__NSCFString JSONFragmentValue]: unrecognized selector sent to instance 0x6994560
and as far as I can tell I have a correctly implemented Category on NSString that implements the JSONFragmentValue.  I suspect that there's something new and different in the way Categories on built-in classes are implemented in Xcode 4.3.2.  I also had a similar problem with a Category on NSNumber and ended up re-writing that as its own independent class (which worked fine).

Any ideas what may have changed to break code like this in Xcode 4.3.2?

**Comment by CMTaylor** [comment]
In browsing the web for other possible solutions to this problem I found this:
https://github.com/rs/SDWebImage/issues/85 

And in the offered solutions there I saw this:

Adding the -all_load flag to 'Other Linker Settings' in my app project, as seen in the first answer here: http://stackoverflow.com/questions/3998483/objective-c-category-causing-unrecognized-selector

This "rang a  bell" with my earlier work on my particular project in an older Xcode.  It said somewhere that this "-all_load" flag was required.  I checked and somehow it hadn't migrated properly to Xcode 4.3.2. I added this to the previously empty "Other Linker Settings" and instantly the exceptions went away and the project worked!  Now I'm going to go back and undo my changes to the Category on NSNumber and see if that works the original way, too!

**Comment by AbeEstrada** [comment]
NSString+HTML is not compatible with Xcode 4.2 because GTMNSString+HTML isn't ARC compatible, it is using `struct`.

You can always add `-fno-objc-arc` to the files (https://code.google.com/p/google-toolbox-for-mac/wiki/ARC_Compatibility)

**Comment by testower** [comment]
Awesome. I added `-fno-objc-arc`as build flag to GTMNSString+HTML.m and NSString+HTML.m under the Compile Sources settings in the Build Phases tab of my Target settings. That solved my problem. Thank you Abe!
