### ISSUE TITLE
Feed item content is moved to summary

### ISSUE THREAD

**Issue by pkuijpers** [mwaterfall/MWFeedParser#52]
When an atom feed item has content but no summary, the content is moved to the summary property of MWFeedItem. According to http://www.ietf.org/rfc/rfc4287, it's perfectly legal for an item to have content and no summary. Moving the content to the summary property can cause confusion.

A better solution may be to just leave the summary empty and keep the content in the Content property of MWFeedItem.

**Comment by mwaterfall** [comment]
Thanks — I'll look into it!

**Comment by mwaterfall** [comment]
Thanks for this suggestion, however I'm happy with the current logic of always having data available in if possible summary. I try to abstract away from the differences between the feed specs, and this way people can just check the one place for the feed content, and if that is empty, there's definitely no content.
