### ISSUE TITLE
data argument not used by format string

### ISSUE THREAD

**Issue by sbentzen** [mwaterfall/MWFeedParser#56]
Hey @mwaterfall, 

noticed this bit of code doesn't use the data argument anywhere in the string or format being appended.
Should it just be pulled out? or is there something else that is to be accomplished?

```
if (ELEMENT_IS_EMPTY(elementName)) {
    [currentText appendFormat:@" />", elementName];
} else {
    [currentText appendFormat:@">", elementName];
}
```

**Comment by jsumners** [comment]
The static analyzer in Xcode 4.4.1 also catches this. I believe the block should be:

``` objective-c
if (ELEMENT_IS_EMPTY(elementName)) {
  [currentText appendString:@" />"];
} else {
  [currentText appendString:@">"];
}
```

**Comment by sbentzen** [comment]
I'll open a pull request later on today.

**Comment by mwaterfall** [comment]
This is now fixed on the master branch. Sorry for taking so long!
