### ISSUE TITLE
Some RSS feed without pubDate or even without updated.

### ISSUE THREAD

**Issue by mikewolfxyou** [mwaterfall/MWFeedParser#6]
HI, I find some rss feed, e.g. http://noc.leaseweb.com/rss/maintenance.php  They mark the time stamp in the description. I really  have no idea how to fix that, cause I try to save the articles into database and show them again. If there is not correct time stamp, it is really hard to order them or decided which articles I have saved when user refresh the feed. I know guid is a way, but sounds also complex, how do you think about that? 
Btw. Good job, thx for the codes. My project is not yet release, when it release, I will note you.

**Comment by mwaterfall** [comment]
The best thing I can advise is to parse out the date yourself from the title or description of the feed, and store it that with the feed items. Then you can compare/sort items using that and do your processing that way. Hope this helps.

Also, the GUID field is not currently parsed but I'm looking into including it soon.

**Comment by mikewolfxyou** [comment]
Thanks for the advise. and finally I hash the titles and save the hashing in to the database, of cause I save the hashing only for the article which has not date information.
