### ISSUE TITLE
Summary with url with /

### ISSUE THREAD

**Issue by RemcoB00** [mwaterfall/MWFeedParser#61]
If a url in my summary is then disappears the part of the URL after the /.

For example:

twitter.com/username

become

twitter.com

Is there a solution for this?

**Comment by mwaterfall** [comment]
Do you have an example feed URL which I can use to replicate this issue?

**Comment by RemcoB00** [comment]
Yes, I'm using a YouTube feed: http://gdata.youtube.com/feeds/api/users/banjomovies/uploads?alt=rss&lr=nl&orderby=published&max-results=50

**Comment by mwaterfall** [comment]
Thanks for the URL, I'll check it out!

**Comment by RemcoB00** [comment]
I've found that this is a mistake in the YouTube feed. And not an error in MWFeedParser.
