### ISSUE TITLE
[Solved] xCode 4.5 and iOS6  -  no suck file or directory libMWFeedParser.a

### ISSUE THREAD

**Issue by flaviopace** [mwaterfall/MWFeedParser#63]
clang: error: no such file or directory: '/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libMWFeedParser.a'

Only when i try to compile my project on my device... If i run it on the simulator, he work fine...

**Comment by ghost** [comment]
If you clean your DeriveedData directory ?

**Comment by flaviopace** [comment]
I cleaned the Project and delete the app on the divice... but the problem is still remain.

http://stackoverflow.com/questions/12557121/xcode-4-5-ios-6-linking-error-with-tapuku-library

This is my same problem...

**Comment by flaviopace** [comment]
clang: error: no such file or directory: '/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libTapkuLibrary.a'
clang: error: no such file or directory: '/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libfmdb.a'
clang: error: no such file or directory: '/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libMGSplitViewController.a'
clang: error: no such file or directory: '/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libMWFeedParser.a'

I deleted all ~/Library/Developer/Xcode/DerivedData

The problen is over all my import library....

**Comment by flaviopace** [comment]
Ld /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Intermediates/DingUnisannio.build/Debug-iphoneos/DingUnisannio.build/Objects-normal/armv7/Unisannio normal armv7
    cd /Users/unicondor/Documents/iosingunisannio-code/DingUnisannio
    setenv IPHONEOS_DEPLOYMENT_TARGET 5.0
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.0.sdk -L/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos -L/Users/unicondor/Documents/iosingunisannio-code/DingUnisannio -F/Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos -filelist /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Intermediates/DingUnisannio.build/Debug-iphoneos/DingUnisannio.build/Objects-normal/armv7/Unisannio.LinkFileList -dead_strip -ObjC -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=5.0 /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libTapkuLibrary.a /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libfmdb.a /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libMGSplitViewController.a /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Products/Debug-iphoneos/libMWFeedParser.a -framework QuartzCore -framework Foundation -framework UIKit -framework CoreGraphics -framework MapKit -framework MessageUI -framework MediaPlayer -framework AVFoundation -framework SystemConfiguration -framework AddressBook -framework CoreLocation -framework AddressBookUI -lxml2 -lsqlite3.0 -framework CFNetwork -framework Security -framework AudioToolbox -o /Users/unicondor/Library/Developer/Xcode/DerivedData/DingUnisannio-czbgknwdwtdvjzfalsaqpvwuqqul/Build/Intermediates/DingUnisannio.build/Debug-iphoneos/DingUnisannio.build/Objects-normal/armv7/Unisannio

My Device it's 3GS with 5.1.1

**Comment by flaviopace** [comment]
Solved!

The problem of external library that has not been compiled for armv7s. If so, I will get this error. To fix the problem, you either need to find the library and compile it with armv7s support, or you can remove armv7s from your valid architectures

**Comment by mwaterfall** [comment]
Good to hear you solved the problem!

**Comment by mnjk** [comment]
hi,

while run my xcode project. i got error like this. i have tried with above changes with my project(remove armv7s from valid architecture).but no use.

once i copy-paste "/libGoogleAnalyticsServices.a" on to path mentioned bellow then, i can able to run xcode project in simulator but not in Device (not able to archive my project for release)

can any of you please help me to solve this issues.

clang: error: no such file or directory: '/Users/Kareems/Library/Developer/Xcode/DerivedData/EventAheadModel-azsrdqingbkxowejmrgzozgxguao/Build/Products/Debug-iphonesimulator/libGoogleAnalyticsServices.a'

![screen shot 2014-06-02 at 3 03 29 pm](https://cloud.githubusercontent.com/assets/7694338/3145571/080a8816-ea39-11e3-9203-8a442a0c6b22.png)

**Comment by mnjk** [comment]
this issue is solved.

i have re-implement the GoogleAnalyticsService newly

**Comment by vizllx** [comment]
-None of the above comment solved the issue-  
People who are stuck in for many hours, and who are searching this post to find how to solve the issue-- 

Here it is:-
1.Drag and Drop MWFeedParser xcodeProj file under your project.
2.Add MWFeedParser.bundle from build phases.
3. ***_---Follow this screenshot----**_*

![screen shot 2014-09-26 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/6848045/4417923/4fc12710-455a-11e4-94ae-bb64a35d30bd.png)
1. ***_---Follow this screenshot----**_*

![screen shot 2014-09-26 at 2 09 17 pm](https://cloud.githubusercontent.com/assets/6848045/4417925/554d6702-455a-11e4-8779-24ba2aa8c247.png)

The main problem we all  are stuck due to configuration we have to do in the  Build settings of XCode.
