### ISSUE TITLE
NSString+HTML <p> tag issue

### ISSUE THREAD

**Issue by renegade78** [mwaterfall/MWFeedParser#67]
Hi,

Just wondering if you had any ideas...

Basically, I'm parsing the item.content into a textfield (to give me complete control over the formatting of the text) and it works really well.

The only issue is that when I convert html to plain text, I lose the <p> tags and so there are no newlines. It appears that the feeds I am parsing do not use <br> tags!

I just wondered if you (or anybody else) had found a way to detect new paragraphs in the html and then keep them when the html is converted into plain text!

Many thanks in advance!

**Comment by mwaterfall** [comment]
Hi there, very sorry for the slow reply. Currently the `-stringByStrippingTags` method doesn't properly handle paragraph tags. It's something I will look into as soon as I have time.

**Comment by renegade78** [comment]
Hey,

No worries - it was a while ago I asked this. I think I solved it by searching for <p> and replacing it with /n - I'd have to check as I'm away from my computer at the moment!!

Cheers.
