### ISSUE TITLE
Me again, Error Code = 3

### ISSUE THREAD

**Issue by mikewolfxyou** [mwaterfall/MWFeedParser#7]
Error Domain=MWFeedParser Code=3 "The operation couldn’t be completed. (NSXMLParserErrorDomain error 9.)" UserInfo=0x7468430 {NSLocalizedDescription=The operation couldn’t be completed. (NSXMLParserErrorDomain error 9.)}

I got above debug error, when I parse the feed:

http://www.facebook.com/feeds/notes.php?id=9445547199&viewer=0&key=f4913b0647&format=rss20

I'm trying to find the reason.

**Comment by mwaterfall** [comment]
Thanks for reporting this, I'll look into it.

**Comment by fgarci** [comment]
Hi there

I'm having a similar issue when parsing the following feed :
http://www.infojobs.net/trabajos.rss/kw_controller/c_10/p_9/om_1_0/

This is the log I'm getting:
2010-09-22 16:56:40.249 MWFeedParser[7392:207] Finished Parsing With Error: Error Domain=MWFeedParser Code=3 "The operation couldn’t be completed. (NSXMLParserErrorDomain error 31.)" UserInfo=0x5f3b1c0 {NSLocalizedDescription=The operation couldn’t be completed. (NSXMLParserErrorDomain error 31.)}

It's quite odd because it has been working for weeks.

Please advise.
Cheers
Fermin

**Comment by mwaterfall** [comment]
Sorry for the delay in getting back to you guys.

@mikewolfxyou: It would appear that the Facebook feed is [invalid](http://validator.w3.org/check?uri=http%3A%2F%2Fwww.facebook.com%2Ffeeds%2Fnotes.php%3Fid%3D9445547199%26viewer%3D0%26key%3Df4913b0647%26format%3Drss20&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.1) and this is why the parser is failing. The NSXMLParser is very strict! I'll have a think about trying to get around this, but at least there's an explanation :)

@fgarci: I'm not sure why it's failing on that feed but I'm trying to figure it out. It is strange that it's been working before and it's now stopped working. Perhaps it's a problem that was introduced recently by a specific feed item? I'll keep looking into it and get back to you when I know more.

**Comment by fgarci** [comment]
Hi Mike 
I sent you the  following to your gmail:

I just want to let you know that parsing fails when parsing XML documents with this instruction <?xml version="1.0" encoding="ISO-8859-15"?>  (i.e this feed http://www.infojobs.net/trabajos.rss/kw_controller/c_10/p_9/om_1_0/)

I found a similar issue in this thread:
http://stackoverflow.com/questions/525001/parsing-a-url-from-xml-with-amp-in-it

I changed your code (see below) accordingly and it works.Not sure it's the best solution though.
// Begin XML parsing
- (void)startParsingData:(NSData *)data {
  
  //Modifications  
  NSString\* astr;
  astr =[[NSString alloc] initWithData:data encoding:NSASCIIStringEncoding];
  astr =[astr stringByReplacingOccurrencesOfString:@"encoding=\"ISO-8859-15\"" withString:@""];
  NSLog(astr);
  NSData\* data2 =[astr dataUsingEncoding:NSUTF8StringEncoding];  
  //End Modifications 
  
  if (data && !feedParser) {
      // Create feed info
      MWFeedInfo *i = [[MWFeedInfo alloc] init];

**Comment by mwaterfall** [comment]
Yep, I've just seen your email and have replied ;)

**Comment by mwaterfall** [comment]
Hey guys,

I've just pushed an update which has much improved handling of various text encodings. Sorry it's taken such a long time, been a busy few months and I haven't been able to work on the parser as much as I would have liked!

Best regards,
Michael
