### ISSUE TITLE
Is there a way to work without a RootViewController?

### ISSUE THREAD

**Issue by cutischmidt** [mwaterfall/MWFeedParser#77]
I try to implement your great FeeedParser into my Project. I only use ViewController because of my special design. So my question is: how can I use the MWFeedParser without a RootViewController? I looks possible to do all the stuff in a normal tableView but i can't get it. 

Best Regards 
cutischmidt

**Comment by mwaterfall** [comment]
Sorry for the slow reply. The feed parser class isn't locked down to any UI elements, you can use it how you wish.
