### ISSUE TITLE
Parsing Block main thread

### ISSUE THREAD

**Issue by whswee** [mwaterfall/MWFeedParser#78]
whenever the parser starts parsing, i can scroll my scrollview, seem that it is blocking the main thread. While i keep scrolling before parsing, the parser will no parse until i stop scrolling. Is there anyway to parse the feed in a background thread so it doesn't block the main ui thread?

**Comment by whswee** [comment]
the connection was set in Async. I have also wrapped the parse code in GDC, but the parse code doesn't get called.

MWFeedParser *feedParser = [[MWFeedParser alloc] initWithFeedURL:[NSURL URLWithString:url]];
    feedParser.name = name;
    feedParser.category = category;
    feedParser.delegate = self;
    feedParser.feedParseType = ParseTypeFull; // Parse feed info and all items
    feedParser.connectionType = ConnectionTypeAsynchronously;
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

```
    [feedParser parse];

});
```

**Comment by whswee** [comment]
after doing some research, seems that NSXMLParser parse method is blocking the main thread. But still cant find a solution to that.

**Comment by mwaterfall** [comment]
You should perform parsing off of the main thread. I'd recommend using an [NSOperation](https://www.google.co.uk/search?q=nsoperation+and+nsoperationqueue).
