### ISSUE TITLE
Parsing Media RSS

### ISSUE THREAD

**Issue by hilikus** [mwaterfall/MWFeedParser#8]
Hi,
first of all I would give you my best congratulations for this project...it works great!! :)
I'm writing because I would like to implement a Yahoo Media RSS parsing: because I'm a very newbie of Objective-C in general, my question is what is/are the method(s) that I have to modify (or implement from scratch) for this purpose and if you can write some lines of codes as example!
Thank you very much in advance.

**Comment by mikewolfxyou** [comment]
There is a example app in the source, isn't it?

**Comment by hilikus** [comment]
Yes, for sure, and I run it in my iPhone Simulator...
But my question is only programmatic: what method and in which way I've to modify in order to manage tags like media:content?
Thanks again.

**Comment by mwaterfall** [comment]
Hi hilikus,

MWFeedParser does not currently support the Media RSS extension. I've added it to the outstanding tasks list however it is not a priority right now. You might wish to fork this project and add the support yourself.

The main work is performed within MWFeedParser.m and in particular the NSXMLParser delegate method -parser:didEndElement:namespaceURI:qualifiedName:. Feel free to have a look around and play with it.

Thanks for getting in touch.
