### ISSUE TITLE
is it possible to change the ' add a comment ' in the bottom of the page ? 

### ISSUE THREAD

**Issue by moheny** [mwaterfall/MWFeedParser#86]
I went throughout the code  multiple of times , read every line and couldn't find where is the ' add a comment ' code that shows in the bottom of the page. I would like to change it to a picture but can't find the code . any help please ?

**Comment by mwaterfall** [comment]
I think you created an issue on the wrong project, or you're confused as to what MWFeedParser is used for.

**Comment by moheny** [comment]
sorry i wasn't specific , that's my bad, it's just slip my fingers :D . 
anyway, what i meant is , when you use MWFeedParser to fetch from WordPress RSS , you get at the end of every feed, ' add a comment ' in the bottom of the page which takes you to the comment section ( which is great ) . 
the problem the ' add a comment ' is too small and i would like to change it to something different , maybe an image but i couldn't find it in your code.
i'm sure the 'add a comment ' is coming from the MWFeed code because WordPress page just has the comments on the same page, and I know you add WordPress support .
i'm not confused about MWFeedParser , it's for sure my favourite add on ! .
thank you for quick answer .

**Comment by mwaterfall** [comment]
@moheny I think you have misunderstood what MWFeedParser is/does. It simply reads in and allows for easy processing of web feed data. What you do with that data is up to you, but it's outside the scope of this project.
