### ISSUE TITLE
Associate MWFeedItem objects with MWFeedInfo objects

### ISSUE THREAD

**Issue by n00neimp0rtant** [mwaterfall/MWFeedParser#92]
As far as I can tell, there's no way to know which feed any given item came from. This seems like a significant issue for any apps that aim to aggregate more than one feed simultaneously. I would suggest adding a `MWFeedInfo *feedInfo` property to MWFeedItem objects.

**Comment by andrewstephenson-v1** [comment]
+1

**Comment by mwaterfall** [comment]
The delegate methods that return the `MWFeedInfo` objects also provide the `MWFeedParser` object that it was processed with — so that will allow you to associate them. Thanks for the recommendation though. I'll take it into consideration.
